# -*- coding: utf-8 -*-
"""Assignment-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/158rzqT8FJwdjXf4Bf504UVqp0tfEQBcm
"""

!pip install yfinance

import yfinance as yf

NIFTY=yf.Ticker('^NSEI')

HDFCLIFE=yf.Ticker('HDFCLIFE.NS')

NIFTY_d=NIFTY.history (period ='10y',auto_adjust="True")['Close']
HDFCLIFE_d=HDFCLIFE.history(period='10y',auto_adjust="True")['Close']

NIFTY_m=NIFTY_d.resample('1M').last()
HDFCLIFE_m=HDFCLIFE_d.resample('1M').last()

NIFTY_mr=NIFTY_m.pct_change().dropna()
HDFCLIFE_mr=HDFCLIFE_m.pct_change().dropna()

import pandas as pd

NK_dt=pd.merge(NIFTY_mr,HDFCLIFE_mr,on='Date')
NK_dt.head()

NK_dt.rename(columns={'Close_x':'NIFTY_mr','Close_y':'HDFCLIFE_mr'},inplace=True)

NK_dt

NK_dt.plot(figsize=(10,4))

train_dt=NK_dt[:-12].dropna()
test_dt=NK_dt[-12:].dropna()

train_dt.head()

"""Now we use train data for analysis 

first we will use adf test to check the stationarity of  the data
"""

from statsmodels.tsa.stattools import adfuller

print('NIFTY_mr')
adfuller(NK_dt.NIFTY_mr)[1]

NIFTY_mr1=adfuller(NK_dt.NIFTY_mr.diff().dropna())[1]
NIFTY_mr1

print('HDFCLIFE_mr')
HDFCLIFE_mr1=adfuller(NK_dt.HDFCLIFE_mr)[1]

HDFCLIFE_mr1=adfuller(NK_dt.HDFCLIFE_mr.diff().dropna())[1]
HDFCLIFE_mr1

train_dt1=train_dt.diff().dropna()
train_dt1.head()

from statsmodels.tsa.api import VAR

model=VAR(train_dt1)

result=model.select_order(maxlags=12)

print(result.summary())

from statsmodels.tsa.statespace.varmax import VARMAX

VARMAX_model=VARMAX(train_dt,order=(3,0),enforce_stationarity=False)

VARMAX_result=VARMAX_model.fit(disp=False)

print(VARMAX_result.summary())

n_forecast=12
predict=VARMAX_result.get_prediction(start=len(train_dt),end=len(train_dt)+n_forecast-1)

predictions=predict.predicted_mean

predictions.columns=[['NIFTY_mr_Predicted','HDFCLIFE_mr_Predicted']]
predictions

test_dt

TvP=pd.concat([test_dt,predictions],axis=1)

TvP.plot(figsize=(10,4))